android_binary (
  name = "apk",
  srcs = glob(["src/main/java/**/*.java"]),
  custom_package = "net.ornew.mnistandroid",
  manifest = "src/main/AndroidManifest.xml",
  resource_files = glob(["src/main/res/**"]),
  deps = [
    "@androidsdk//com.android.support:appcompat-v7-25.0.0",
  ],
)
