android_binary (
  name = "apk",
  srcs = glob(["src/main/java/**/*.java"]),
  custom_package = "net.ornew.mnistandroid",
  manifest = "src/main/AndroidManifest.xml",
  resource_files = glob(["src/main/res/**"]),
  deps = ["//external:android/appcompat_v4", "//external:android/appcompat_v7"],
)
